// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDZCj_PjW03IuhSpdbrJeDwb2a3gsTbaFQ',
//     appId: '1:460623984033:web:9c2ed8581f36d1455d07e0',
//     messagingSenderId: '460623984033',
//     projectId: 'vua-gao-intership',
//     authDomain: 'vua-gao-intership.firebaseapp.com',
//     storageBucket: 'vua-gao-intership.appspot.com',
//     measurementId: 'G-E4R1HMPT8W',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAjUG36_6cyS0EtYLeVJMG8zudKoPOHA1w',
//     appId: '1:460623984033:android:2c4102086d3126045d07e0',
//     messagingSenderId: '460623984033',
//     projectId: 'vua-gao-intership',
//     storageBucket: 'vua-gao-intership.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCUWGglzJIq0Gi2GMOmRcpiGg7511dWxuk',
//     appId: '1:460623984033:ios:f52c51517e876e925d07e0',
//     messagingSenderId: '460623984033',
//     projectId: 'vua-gao-intership',
//     storageBucket: 'vua-gao-intership.appspot.com',
//     iosBundleId: 'com.haovo.vuaGao',
//   );
// }
